### PR TITLE
Switch over to Rails4

### PR DESCRIPTION
**Pull request by pcreux**
@eshaiju did a great job migrating this demo over to rails4. I've fixed a few things here and there.

This demo is currently running at http://demo-aa-rails4.herokuapp.com/admin

Notes:

* hoptoad is not being used anymore
* comments are disabled. This might prevent bots from messing around with the app.
* Integration tests for the store have been removed

### CODE REVIEW

**Comment by eshaiju** [comment]
HI @timoschilling 

What happen to this PR?

**Comment by timoschilling** [comment]
I think we should merge this.

@pcreux can you add me to the heruko app? Then can we use your app as base for demo.activeadmin.info, I will change the DNS, if you agree.

**Comment by pcreux** [comment]
@timo, I could just migrate the existing app to cedar14 and push this code
to it.

On a separate note, would using Cloudflare help us staying up and running?

**Comment by timoschilling** [comment]
@pcreux do it

**Comment by pcreux** [comment]
Done & deployed

**Comment by timoschilling** [comment]
@pcreux :+1:

**Pull request merged**
