### PR TITLE
Use ruby 2.6

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
Not sure how heroku chooses its ruby version. Does it read it from the lock file?

### CODE REVIEW

**Comment by javierjulio** [comment]
It uses the ruby version from the `Gemfile`. I looked at ours and sees it allows multiple versions. I haven't seen that format used for the `ruby` method before. Cool! With the lock file update, from what I can tell it should be using that. More info here: https://devcenter.heroku.com/articles/ruby-versions

**Comment by deivid-rodriguez** [comment]
Yay! It worked as documented :+1:.

**Comment by javierjulio** [comment]
Awesome thanks! Let me know when this is ready and we'll get it out. 😎

**Comment by deivid-rodriguez** [comment]
It's ready! :)

**Pull request merged**
